overrides:
  nodemailer@<7.0.7: '>=7.0.7'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  '@smithy/config-resolver@<4.4.0': '>=4.4.0'
  next@>=15.6.0-canary.0 <16.1.5: '>=16.1.5'
  next@>=16.0.0-beta.0 <16.0.11: '>=16.0.11'
  fast-xml-parser@>=4.3.6 <=5.3.3: '>=5.3.4'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  nodemailer@<=7.0.10: '>=7.0.11'
  next@>=16.0.0-beta.0 <16.1.5: '>=16.1.5'
